### ISSUE TITLE
Shell-customized server-side decorations

### ISSUE THREAD

**Issue by AlanGriffiths** [canonical/mir#3372]
Shells ought to be able to customise the default SSD Mir provides (currently only for X11 clients)

**Comment by Conan-Kudo** [comment]
This should be done alongside #3371 so that SSDs are unified for both X11 and Wayland clients.

**Comment by Saviq** [comment]
Fixed by #3425

**Comment by AlanGriffiths** [comment]
Not fixed. There's still no customization point for Mir's decorations

**Comment by Saviq** [comment]
> Not fixed. There's still no customization point for Mir's decorations

Was not in the title xD

**Comment by Saviq** [comment]
Ref.: https://discourse.ubuntu.com/t/mir-office-hours-2024-07-25-15-00utc/46478/3
